# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c51b7ef55548695efdffcd05ccff2fc25eafc4d561e808b4f4a32224645e17a4e5ec38bbf9186b5234d92da08740a9f8691a779043d4da3c8d50ca42807f7bb

test:
  secret_key_base: 04e2083a3f100468cdb4702ffb0f2c540a315426deee47c78da40b3c24575355f813ee912ece02a3f200d66318420f55620a45583a991a6b630677a01598e2cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
